services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - PORT=8761
    networks:
      - event-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
      - APP_JWT_SECRET=your-very-long-secret-key-here-min-32-chars
    depends_on:
      service-registry:
        condition: service_started
    networks:
      - event-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - PORT=8086
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
      - APP_JWT_SECRET=your-very-long-secret-key-here-min-32-chars
    depends_on:
      service-registry:
        condition: service_started
    networks:
      - event-net

  event-service:
    build: ./event-service
    container_name: event-service
    environment:
      - PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
      - APP_JWT_SECRET=your-very-long-secret-key-here-min-32-chars
    depends_on:
      service-registry:
        condition: service_started
    networks:
      - event-net

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
    depends_on:
      service-registry:
        condition: service_started
    networks:
      - event-net

  registration-service:
    build: ./registration-service
    container_name: registration-service
    environment:
      - PORT=8084
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
      - APP_JWT_SECRET=your-very-long-secret-key-here-min-32-chars
      - APP_GATEWAY_URL=http://api-gateway:8080
    depends_on:
      - service-registry
      - api-gateway
    networks:
      - event-net

  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment:
      - PORT=8085
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka
    depends_on:
      service-registry:
        condition: service_started
    networks:
      - event-net

networks:
  event-net:
    driver: bridge
